Revert "add inplace operation"
This reverts commit 2b191082fce6d0a5977d0c26694266a52b355eb0.

spike_seq, self.v_seq = neuron_kernel.MultiStepIFNodePTT.apply(
RuntimeError: If your Function modifies inplace an input that is a view of another Tensor, your Function cannot return more than one Tensor. This is not supported by the current autograd engine. You should either make sure the input is not a view (using .clone() for example) or make your Function only return one Tensor (potentially splitting it into two Functions: one doing the inplace that returns a single Tensor and a second one that does the other operations). You can ask on the forum https://discuss.pytorch.org/ if you need help to do this change.